### ISSUE TITLE
ctx.route.includes is not a function when passing a function to generate.routes

### ISSUE THREAD

**Issue by Zae** [d3xter-dev/sitemap-module-nuxt-3#19]
Hi,

I get this error when trying to pass a function to `generate.routes`, [according to the nuxt docs this should be possible](https://nuxt.com/docs/api/configuration/nuxt-config#generate) (like it was in nuxt 2), however when doing so, I get the following error.

```
 ERROR  ctx.route.includes is not a function                                                                                                                                                          
  at node_modules/@funken-studio/sitemap-nuxt-3/dist/module.mjs:418:2
  at node_modules/hookable/dist/index.mjs:39:82
  at async prerender (node_modules/nitropack/dist/shared/nitro.c8278d90.mjs:2961:7)
  at async node_modules/nuxt/dist/index.mjs:1675:7
  at async build (node_modules/nuxt/dist/index.mjs:2236:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:56:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/generate.mjs:32:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
```

Using: 
- @funken-studio/sitemap-nuxt-3@4.0.4
- nuxt@3.0.0

**Comment by ErwinAI** [comment]
Also running into this problem

**Comment by Testottest** [comment]
Are there any solutions?
